# This is used by Travis CI site in order
# to produce a PDF file out of LuaLaTeX.

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker run --rm -d -it -v $(pwd):/tmp -w /tmp --name alpine_texlive alpine
  - docker exec alpine_texlive apk add --update texlive-full > log.txt
  - grep -m 1 "LuaTeX, Version" log.txt && tail -1 log.txt && rm log.txt

script:
  # Create temporary directory
  - mkdir hyphenation
  # Concatenate English and Greek hyphenation rules
  - docker exec alpine_texlive
    cat /usr/share/texmf-dist/tex/generic/hyphen/hyphen.tex
    /usr/share/texmf-dist/tex/generic/hyph-utf8/patterns/tex/hyph-el-monoton.tex
    > hyphenation/dumyhyph.tex
  # Install joined hyphenation rules
  - docker exec -w /tmp/hyphenation alpine_texlive
    mktexfmt lualatex.fmt
  # Install LuaLaTeX
  - docker exec -w /usr/bin alpine_texlive
    ln -s luatex lualatex
  # Produce PDF
  - docker exec alpine_texlive
    latexmk -lualatex PhD_Report_2018.tex

after_success:
  # Decrypt private key for accessing web server
  - openssl aes-256-cbc -K $encrypted_3999ae8aa3be_key
    -iv $encrypted_3999ae8aa3be_iv
    -in key_for_uploading.pem.enc
    -out key_for_uploading.pem -d
  - chmod 600 key_for_uploading.pem
  # Upload to web server
  - scp -i key_for_uploading.pem -o StrictHostKeyChecking=no
    PhD_Report_2018.pdf pothitos@linux19.di.uoa.gr:public_html/papers/
  - ssh -i key_for_uploading.pem pothitos@linux19.di.uoa.gr
    chmod o+r public_html/papers/PhD_Report_2018.pdf
