# This is used by Travis CI site in order
# to produce a PDF file out of LaTeX.

addons:
  apt:
    packages:
      - texlive-full

script:
  - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode"
    PhD_Report_2018.tex

after_success:
  # Decrypt private key for accessing web server
  - openssl aes-256-cbc -K $encrypted_6c6bd1d07a2a_key
    -iv $encrypted_6c6bd1d07a2a_iv
    -in key_for_uploading.pem.enc
    -out key_for_uploading.pem -d
  - chmod 600 key_for_uploading.pem
  # Upload to web server
  - scp -i key_for_uploading.pem -o StrictHostKeyChecking=no
    PhD_Report_2018.pdf pothitos@linux19.di.uoa.gr:public_html/papers/
  - ssh -i key_for_uploading.pem pothitos@linux19.di.uoa.gr
    chmod o+r public_html/papers/PhD_Report_2018.pdf
